GET http://localhost:8080/

###

GET http://localhost:8080/3willows/html-css-export-word.svg

###
GET http://localhost:8080/3willows/3willows.github.io.svg

###
GET http://localhost:8080/3willows/mean-book-samples.svg